  data=[
  {
    "primaryTitle": "Back in Action",
    "originalTitle": "Back in Action",
    "views": 164700000,
    "startYear": 2025,
    "runtimeMinutes": 114,
    "genre": "Comedy",
    "primaryCast": 16,
    "male": 9,
    "female": 6,
    "nonbinary": 1,
    "percentageFemale": 38,
    "rating": 5.9,
    "fullCast": 100,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Straw",
    "originalTitle": "Straw",
    "views": 102900000,
    "startYear": 2025,
    "runtimeMinutes": 105,
    "genre": "Drama",
    "primaryCast": 15,
    "male": 7,
    "female": 8,
    "nonbinary": 0,
    "percentageFemale": 53,
    "rating": 6.5,
    "fullCast": 54,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Life List",
    "originalTitle": "The Life List",
    "views": 95500000,
    "startYear": 2025,
    "runtimeMinutes": 123,
    "genre": "Romance",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.8,
    "fullCast": 52,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Exterritorial",
    "originalTitle": "Exterritorial",
    "views": 87500000,
    "startYear": 2025,
    "runtimeMinutes": 109,
    "genre": "Thriller",
    "primaryCast": 9,
    "male": 4,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 56,
    "rating": 5.8,
    "fullCast": 30,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Havoc",
    "originalTitle": "Havoc",
    "views": 86900000,
    "startYear": 2025,
    "runtimeMinutes": 107,
    "genre": "Action",
    "primaryCast": 14,
    "male": 10,
    "female": 3,
    "nonbinary": 1,
    "percentageFemale": 21,
    "rating": 5.6,
    "fullCast": 72,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Secret Life of Pets 2",
    "originalTitle": "The Secret Life of Pets 2",
    "views": 74500000,
    "startYear": 2019,
    "runtimeMinutes": 86,
    "genre": "Animation",
    "primaryCast": 12,
    "male": 8,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 6.4,
    "fullCast": 44,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Electric State",
    "originalTitle": "The Electric State",
    "views": 74200000,
    "startYear": 2025,
    "runtimeMinutes": 125,
    "genre": "Sci Fi",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.9,
    "fullCast": 100,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Counterstrike",
    "originalTitle": "Contraataque",
    "views": 71300000,
    "startYear": 2025,
    "runtimeMinutes": 84,
    "genre": "Action",
    "primaryCast": 8,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 6,
    "fullCast": 23,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Ad Vitam",
    "originalTitle": "Ad Vitam",
    "views": 69800000,
    "startYear": 2025,
    "runtimeMinutes": 98,
    "genre": "Sci Fi",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 5.9,
    "fullCast": 52,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Despicable Me 4",
    "originalTitle": "Despicable Me 4",
    "views": 69800000,
    "startYear": 2024,
    "runtimeMinutes": 94,
    "genre": "Animation",
    "primaryCast": 14,
    "male": 7,
    "female": 7,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 6.2,
    "fullCast": 37,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Secret Life of Pets",
    "originalTitle": "The Secret Life of Pets",
    "views": 65900000,
    "startYear": 2016,
    "runtimeMinutes": 86,
    "genre": "Animation",
    "primaryCast": 14,
    "male": 10,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 29,
    "rating": 6.5,
    "fullCast": 31,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Kinda Pregnant",
    "originalTitle": "Kinda Pregnant",
    "views": 58900000,
    "startYear": 2025,
    "runtimeMinutes": 97,
    "genre": "Comedy",
    "primaryCast": 12,
    "male": 6,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 4.9,
    "fullCast": 100,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Nonnas",
    "originalTitle": "Nonnas",
    "views": 57600000,
    "startYear": 2025,
    "runtimeMinutes": 111,
    "genre": "Comedy",
    "primaryCast": 7,
    "male": 3,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 57,
    "rating": 6.8,
    "fullCast": 50,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "iHostage",
    "originalTitle": "iHostage",
    "views": 57400000,
    "startYear": 2025,
    "runtimeMinutes": 100,
    "genre": "Thriller",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.7,
    "fullCast": 40,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "La Dolce Villa",
    "originalTitle": "La Dolce Villa",
    "views": 55500000,
    "startYear": 2025,
    "runtimeMinutes": 99,
    "genre": "Romance",
    "primaryCast": 7,
    "male": 5,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 29,
    "rating": 6,
    "fullCast": 32,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Boss Baby",
    "originalTitle": "The Boss Baby",
    "views": 55200000,
    "startYear": 2017,
    "runtimeMinutes": 97,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 7,
    "female": 1,
    "nonbinary": 0,
    "percentageFemale": 13,
    "rating": 6.3,
    "fullCast": 24,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Minions",
    "originalTitle": "Minions",
    "views": 54100000,
    "startYear": 2015,
    "runtimeMinutes": 91,
    "genre": "Animation",
    "primaryCast": 15,
    "male": 11,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 27,
    "rating": 6.4,
    "fullCast": 53,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Shrek",
    "originalTitle": "Shrek",
    "views": 53500000,
    "startYear": 2001,
    "runtimeMinutes": 90,
    "genre": "Animation",
    "primaryCast": 16,
    "male": 13,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 19,
    "rating": 7.9,
    "fullCast": 28,
    "leadGender": "male",
    "directorGender": "both",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Plankton: The Movie",
    "originalTitle": "Plankton: The Movie",
    "views": 50600000,
    "startYear": 2025,
    "runtimeMinutes": 87,
    "genre": "Animation",
    "primaryCast": 9,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 44,
    "rating": 5.3,
    "fullCast": 19,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Despicable Me 3",
    "originalTitle": "Despicable Me 3",
    "views": 49100000,
    "startYear": 2017,
    "runtimeMinutes": 89,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 5,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 6.3,
    "fullCast": 38,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Carry-On",
    "originalTitle": "Carry-On",
    "views": 47700000,
    "startYear": 2024,
    "runtimeMinutes": 119,
    "genre": "Thriller",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.5,
    "fullCast": 100,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Despicable Me 2",
    "originalTitle": "Despicable Me 2",
    "views": 45900000,
    "startYear": 2013,
    "runtimeMinutes": 98,
    "genre": "Animation",
    "primaryCast": 13,
    "male": 7,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 46,
    "rating": 7.3,
    "fullCast": 37,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Shrek 2",
    "originalTitle": "Shrek 2",
    "views": 44500000,
    "startYear": 2004,
    "runtimeMinutes": 93,
    "genre": "Animation",
    "primaryCast": 15,
    "male": 12,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 20,
    "rating": 7.4,
    "fullCast": 27,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Bad Influence",
    "originalTitle": "Mala influencia",
    "views": 44100000,
    "startYear": 2025,
    "runtimeMinutes": 106,
    "genre": "Romance",
    "primaryCast": 10,
    "male": 4,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 60,
    "rating": 4.2,
    "fullCast": 55,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "K.O.",
    "originalTitle": "K.O.",
    "views": 43500000,
    "startYear": 2025,
    "runtimeMinutes": 86,
    "genre": "Action",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 5.8,
    "fullCast": 46,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "A Widow's Game",
    "originalTitle": "La viuda negra",
    "views": 41300000,
    "startYear": 2025,
    "runtimeMinutes": 122,
    "genre": "Thriller",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 6.2,
    "fullCast": 53,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Sing",
    "originalTitle": "Sing",
    "views": 41100000,
    "startYear": 2016,
    "runtimeMinutes": 108,
    "genre": "Animation",
    "primaryCast": 11,
    "male": 7,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 36,
    "rating": 7.1,
    "fullCast": 56,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Venom: The Last Dance",
    "originalTitle": "Venom: The Last Dance",
    "views": 39600000,
    "startYear": 2024,
    "runtimeMinutes": 110,
    "genre": "Sci Fi",
    "primaryCast": 12,
    "male": 7,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 42,
    "rating": 6,
    "fullCast": 39,
    "leadGender": "male",
    "directorGender": "female",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Super Mario Bros. Movie",
    "originalTitle": "The Super Mario Bros. Movie",
    "views": 38900000,
    "startYear": 2023,
    "runtimeMinutes": 92,
    "genre": "Animation",
    "primaryCast": 17,
    "male": 14,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 18,
    "rating": 7,
    "fullCast": 40,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Croods",
    "originalTitle": "The Croods",
    "views": 38200000,
    "startYear": 2013,
    "runtimeMinutes": 98,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 5,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 7.1,
    "fullCast": 8,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "KPop Demon Hunters",
    "originalTitle": "KPop Demon Hunters",
    "views": 36700000,
    "startYear": 2025,
    "runtimeMinutes": 95,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 4,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 7.6,
    "fullCast": 43,
    "leadGender": "female",
    "directorGender": "both",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Despicable Me",
    "originalTitle": "Despicable Me",
    "views": 36100000,
    "startYear": 2010,
    "runtimeMinutes": 95,
    "genre": "Animation",
    "primaryCast": 18,
    "male": 12,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 7.6,
    "fullCast": 33,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Honeymoon Crasher",
    "originalTitle": "Lune de miel avec ma m√®re",
    "views": 34900000,
    "startYear": 2025,
    "runtimeMinutes": 93,
    "genre": "Comedy",
    "primaryCast": 7,
    "male": 4,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 43,
    "rating": 5.6,
    "fullCast": 25,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "PAW Patrol: The Mighty Movie",
    "originalTitle": "PAW Patrol: The Mighty Movie",
    "views": 34600000,
    "startYear": 2023,
    "runtimeMinutes": 88,
    "genre": "Animation",
    "primaryCast": 16,
    "male": 12,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.9,
    "fullCast": 47,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Kraven the Hunter",
    "originalTitle": "Kraven the Hunter",
    "views": 34500000,
    "startYear": 2024,
    "runtimeMinutes": 127,
    "genre": "Action",
    "primaryCast": 10,
    "male": 8,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 20,
    "rating": 5.5,
    "fullCast": 66,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Demon City",
    "originalTitle": "Oni Goroshi",
    "views": 33600000,
    "startYear": 2025,
    "runtimeMinutes": 106,
    "genre": "Action",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 5.4,
    "fullCast": 25,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Emoji Movie",
    "originalTitle": "The Emoji Movie",
    "views": 33600000,
    "startYear": 2017,
    "runtimeMinutes": 86,
    "genre": "Animation",
    "primaryCast": 13,
    "male": 6,
    "female": 7,
    "nonbinary": 0,
    "percentageFemale": 54,
    "rating": 3.5,
    "fullCast": 62,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Bullet Train Explosion",
    "originalTitle": "Shinkansen daibakuha",
    "views": 33400000,
    "startYear": 2025,
    "runtimeMinutes": 134,
    "genre": "Action",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.2,
    "fullCast": 84,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Bee Movie",
    "originalTitle": "Bee Movie",
    "views": 33400000,
    "startYear": 2007,
    "runtimeMinutes": 91,
    "genre": "Animation",
    "primaryCast": 17,
    "male": 14,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 18,
    "rating": 6.1,
    "fullCast": 37,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "A Deadly American Marriage",
    "originalTitle": "A Deadly American Marriage",
    "views": 32300000,
    "startYear": 2025,
    "runtimeMinutes": 102,
    "genre": "Documentary",
    "primaryCast": 18,
    "male": 12,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 6.6,
    "fullCast": 23,
    "leadGender": "male",
    "directorGender": "female",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Last Bullet",
    "originalTitle": "Balle perdue 3",
    "views": 31300000,
    "startYear": 2025,
    "runtimeMinutes": 111,
    "genre": "Action",
    "primaryCast": 12,
    "male": 9,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.3,
    "fullCast": 22,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Mission: Impossible - Dead Reckoning Part One",
    "originalTitle": "Mission: Impossible - Dead Reckoning Part One",
    "views": 31100000,
    "startYear": 2023,
    "runtimeMinutes": 163,
    "genre": "Action",
    "primaryCast": 14,
    "male": 9,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 36,
    "rating": 7.6,
    "fullCast": 100,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Rebel Ridge",
    "originalTitle": "Rebel Ridge",
    "views": 31100000,
    "startYear": 2024,
    "runtimeMinutes": 131,
    "genre": "Thriller",
    "primaryCast": 12,
    "male": 10,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 17,
    "rating": 6.8,
    "fullCast": 32,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Equalizer 2",
    "originalTitle": "The Equalizer 2",
    "views": 29700000,
    "startYear": 2018,
    "runtimeMinutes": 121,
    "genre": "Action",
    "primaryCast": 10,
    "male": 8,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 20,
    "rating": 6.7,
    "fullCast": 100,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Squad 36",
    "originalTitle": "Bastion 36",
    "views": 29300000,
    "startYear": 2025,
    "runtimeMinutes": 124,
    "genre": "Action",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 5.5,
    "fullCast": 34,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "The Six Triple Eight",
    "originalTitle": "The Six Triple Eight",
    "views": 28800000,
    "startYear": 2024,
    "runtimeMinutes": 127,
    "genre": "Drama",
    "primaryCast": 14,
    "male": 3,
    "female": 11,
    "nonbinary": 0,
    "percentageFemale": 79,
    "rating": 6.7,
    "fullCast": 100,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Lucca's World",
    "originalTitle": "Los dos hemisferios de Lucca",
    "views": 28800000,
    "startYear": 2025,
    "runtimeMinutes": 96,
    "genre": "Drama",
    "primaryCast": 10,
    "male": 8,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 20,
    "rating": 6.9,
    "fullCast": 21,
    "leadGender": "male",
    "directorGender": "female",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Hotel Transylvania 2",
    "originalTitle": "Hotel Transylvania 2",
    "views": 28500000,
    "startYear": 2015,
    "runtimeMinutes": 89,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 7,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 30,
    "rating": 6.6,
    "fullCast": 85,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Union",
    "originalTitle": "The Union",
    "views": 28400000,
    "startYear": 2024,
    "runtimeMinutes": 107,
    "genre": "Action",
    "primaryCast": 12,
    "male": 9,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.5,
    "fullCast": 69,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Puss in Boots: The Last Wish",
    "originalTitle": "Puss in Boots: The Last Wish",
    "views": 28000000,
    "startYear": 2022,
    "runtimeMinutes": 102,
    "genre": "Animation",
    "primaryCast": 9,
    "male": 6,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 29,
    "rating": 7.8,
    "fullCast": 29,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Uncharted",
    "originalTitle": "Uncharted",
    "views": 27600000,
    "startYear": 2022,
    "runtimeMinutes": 116,
    "genre": "Action",
    "primaryCast": 13,
    "male": 9,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 31,
    "rating": 6.3,
    "fullCast": 32,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Hotel Transylvania 3: Summer Vacation",
    "originalTitle": "Hotel Transylvania 3: Summer Vacation",
    "views": 27300000,
    "startYear": 2018,
    "runtimeMinutes": 97,
    "genre": "Animation",
    "primaryCast": 16,
    "male": 10,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 6.3,
    "fullCast": 48,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Twister: Caught in the Storm",
    "originalTitle": "The Twister: Caught in the Storm",
    "views": 27300000,
    "startYear": 2025,
    "runtimeMinutes": 89,
    "genre": "Documentary",
    "primaryCast": 18,
    "male": 15,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 17,
    "rating": 6.8,
    "fullCast": 18,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Sing: Thriller",
    "originalTitle": "Sing: Thriller",
    "views": 27000000,
    "startYear": 2024,
    "runtimeMinutes": 11,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 4,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 6.6,
    "fullCast": 8,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "We Can Be Heroes",
    "originalTitle": "We Can Be Heroes",
    "views": 26900000,
    "startYear": 2020,
    "runtimeMinutes": 100,
    "genre": "Animation",
    "primaryCast": 14,
    "male": 7,
    "female": 7,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 4.7,
    "fullCast": 73,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Titan: The OceanGate Submersible Disaster",
    "originalTitle": "Titan: The OceanGate Submersible Disaster",
    "views": 26400000,
    "startYear": 2025,
    "runtimeMinutes": 111,
    "genre": "Documentary",
    "primaryCast": 13,
    "male": 10,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 23,
    "rating": 6.7,
    "fullCast": 37,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Sonic the Hedgehog",
    "originalTitle": "Sonic the Hedgehog",
    "views": 26400000,
    "startYear": 2020,
    "runtimeMinutes": 99,
    "genre": "Action",
    "primaryCast": 10,
    "male": 8,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 20,
    "rating": 6.5,
    "fullCast": 55,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Grinch",
    "originalTitle": "The Grinch",
    "views": 25900000,
    "startYear": 2018,
    "runtimeMinutes": 85,
    "genre": "Animation",
    "primaryCast": 11,
    "male": 7,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 36,
    "rating": 6.4,
    "fullCast": 45,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Trolls Band Together",
    "originalTitle": "Trolls Band Together",
    "views": 25200000,
    "startYear": 2023,
    "runtimeMinutes": 91,
    "genre": "Animation",
    "primaryCast": 16,
    "male": 12,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6,
    "fullCast": 45,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Den of Thieves: Pantera",
    "originalTitle": "Den of Thieves: Pantera",
    "views": 25000000,
    "startYear": 2025,
    "runtimeMinutes": 144,
    "genre": "Action",
    "primaryCast": 11,
    "male": 9,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 18,
    "rating": 6.3,
    "fullCast": 55,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Nr. 24",
    "originalTitle": "Nr. 24",
    "views": 24200000,
    "startYear": 2024,
    "runtimeMinutes": 111,
    "genre": "Drama",
    "primaryCast": 10,
    "male": 7,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 30,
    "rating": 7.5,
    "fullCast": 59,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Inside Man: Most Wanted",
    "originalTitle": "Inside Man: Most Wanted",
    "views": 24200000,
    "startYear": 2019,
    "runtimeMinutes": 105,
    "genre": "Thriller",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.6,
    "fullCast": 39,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Red Notice",
    "originalTitle": "Red Notice",
    "views": 23700000,
    "startYear": 2021,
    "runtimeMinutes": 118,
    "genre": "Action",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.3,
    "fullCast": 84,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Shrek the Third",
    "originalTitle": "Shrek the Third",
    "views": 23100000,
    "startYear": 2007,
    "runtimeMinutes": 93,
    "genre": "Animation",
    "primaryCast": 14,
    "male": 11,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 21,
    "rating": 6.1,
    "fullCast": 45,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Fear Street: Prom Queen",
    "originalTitle": "Fear Street: Prom Queen",
    "views": 22900000,
    "startYear": 2025,
    "runtimeMinutes": 90,
    "genre": "Thriller",
    "primaryCast": 14,
    "male": 4,
    "female": 9,
    "nonbinary": 0,
    "percentageFemale": 64,
    "rating": 5.1,
    "fullCast": 39,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Jewel Thief: The Heist Begins",
    "originalTitle": "Jewel Thief: The Heist Begins",
    "views": 22700000,
    "startYear": 2025,
    "runtimeMinutes": 116,
    "genre": "Action",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 4.1,
    "fullCast": 21,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Trainwreck: Poop Cruise",
    "originalTitle": "Trainwreck: Poop Cruise",
    "views": 22700000,
    "startYear": 2025,
    "runtimeMinutes": 55,
    "genre": "Documentary",
    "primaryCast": 18,
    "male": 11,
    "female": 7,
    "nonbinary": 0,
    "percentageFemale": 39,
    "rating": 6,
    "fullCast": 22,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Ma",
    "originalTitle": "Ma",
    "views": 22500000,
    "startYear": 2019,
    "runtimeMinutes": 99,
    "genre": "Thriller",
    "primaryCast": 10,
    "male": 4,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 60,
    "rating": 5.6,
    "fullCast": 38,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Leo",
    "originalTitle": "Leo",
    "views": 22300000,
    "startYear": 2023,
    "runtimeMinutes": 102,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 7,
    "fullCast": 75,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Delicious",
    "originalTitle": "Delicious",
    "views": 22200000,
    "startYear": 2025,
    "runtimeMinutes": 102,
    "genre": "Drama",
    "primaryCast": 12,
    "male": 7,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 42,
    "rating": 4.4,
    "fullCast": 12,
    "leadGender": "female",
    "directorGender": "female",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Trolls",
    "originalTitle": "Trolls",
    "views": 22100000,
    "startYear": 2016,
    "runtimeMinutes": 92,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 6.4,
    "fullCast": 32,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Heart Knows",
    "originalTitle": "Coraz√≥n delator",
    "views": 22000000,
    "startYear": 2025,
    "runtimeMinutes": 89,
    "genre": "Romance",
    "primaryCast": 9,
    "male": 6,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 5.8,
    "fullCast": 18,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Plane",
    "originalTitle": "Plane",
    "views": 21900000,
    "startYear": 2023,
    "runtimeMinutes": 107,
    "genre": "Action",
    "primaryCast": 11,
    "male": 8,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 27,
    "rating": 6.5,
    "fullCast": 47,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The SpongeBob Movie: Sponge Out of Water",
    "originalTitle": "The SpongeBob Movie: Sponge Out of Water",
    "views": 21800000,
    "startYear": 2015,
    "runtimeMinutes": 92,
    "genre": "Animation",
    "primaryCast": 7,
    "male": 6,
    "female": 1,
    "nonbinary": 0,
    "percentageFemale": 14,
    "rating": 6,
    "fullCast": 62,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Hotel Transylvania",
    "originalTitle": "Hotel Transylvania",
    "views": 21300000,
    "startYear": 2012,
    "runtimeMinutes": 91,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 7,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 30,
    "rating": 7,
    "fullCast": 60,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Sonic the Hedgehog 2",
    "originalTitle": "Sonic the Hedgehog 2",
    "views": 21000000,
    "startYear": 2022,
    "runtimeMinutes": 122,
    "genre": "Action",
    "primaryCast": 10,
    "male": 7,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 30,
    "rating": 6.5,
    "fullCast": 90,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Bogota: City of the Lost",
    "originalTitle": "Bogota: City of the Lost",
    "views": 20900000,
    "startYear": 2024,
    "runtimeMinutes": 108,
    "genre": "Drama",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 5.4,
    "fullCast": 15,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Fast X",
    "originalTitle": "Fast X",
    "views": 20600000,
    "startYear": 2023,
    "runtimeMinutes": 141,
    "genre": "Action",
    "primaryCast": 10,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 5.7,
    "fullCast": 62,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Equalizer 3",
    "originalTitle": "The Equalizer 3",
    "views": 20600000,
    "startYear": 2023,
    "runtimeMinutes": 109,
    "genre": "Action",
    "primaryCast": 8,
    "male": 6,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 25,
    "rating": 6.8,
    "fullCast": 51,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Damsel",
    "originalTitle": "Damsel",
    "views": 20400000,
    "startYear": 2024,
    "runtimeMinutes": 110,
    "genre": "Action",
    "primaryCast": 8,
    "male": 3,
    "female": 5,
    "nonbinary": 0,
    "percentageFemale": 63,
    "rating": 6.1,
    "fullCast": 31,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "yes"
  },
  {
    "primaryTitle": "Back to the Outback",
    "originalTitle": "Back to the Outback",
    "views": 20200000,
    "startYear": 2021,
    "runtimeMinutes": 95,
    "genre": "Animation",
    "primaryCast": 12,
    "male": 6,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 6.5,
    "fullCast": 27,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Minions: The Rise of Gru",
    "originalTitle": "Minions: The Rise of Gru",
    "views": 20100000,
    "startYear": 2022,
    "runtimeMinutes": 87,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 5,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 6.5,
    "fullCast": 54,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Bad Boys: Ride or Die",
    "originalTitle": "Bad Boys: Ride or Die",
    "views": 19600000,
    "startYear": 2024,
    "runtimeMinutes": 115,
    "genre": "Comedy",
    "primaryCast": 6,
    "male": 4,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 33,
    "rating": 6.5,
    "fullCast": 69,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Norbit",
    "originalTitle": "Norbit",
    "views": 19600000,
    "startYear": 2007,
    "runtimeMinutes": 102,
    "genre": "Comedy",
    "primaryCast": 10,
    "male": 9,
    "female": 1,
    "nonbinary": 0,
    "percentageFemale": 10,
    "rating": 4.3,
    "fullCast": 100,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Woody Woodpecker Goes to Camp",
    "originalTitle": "Woody Woodpecker Goes to Camp",
    "views": 19600000,
    "startYear": 2024,
    "runtimeMinutes": 100,
    "genre": "Animation",
    "primaryCast": 8,
    "male": 5,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 4.5,
    "fullCast": 24,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Under Paris",
    "originalTitle": "Sous la Seine",
    "views": 19300000,
    "startYear": 2024,
    "runtimeMinutes": 104,
    "genre": "Drama",
    "primaryCast": 8,
    "male": 5,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 5.2,
    "fullCast": 51,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Dungeons & Dragons: Honor Among Thieves",
    "originalTitle": "Dungeons & Dragons: Honor Among Thieves",
    "views": 19200000,
    "startYear": 2023,
    "runtimeMinutes": 134,
    "genre": "Action",
    "primaryCast": 10,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 7.2,
    "fullCast": 86,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Twilight",
    "originalTitle": "Twilight",
    "views": 19100000,
    "startYear": 2008,
    "runtimeMinutes": 122,
    "genre": "Romance",
    "primaryCast": 15,
    "male": 9,
    "female": 6,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 5.3,
    "fullCast": 48,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "White Chicks",
    "originalTitle": "White Chicks",
    "views": 18900000,
    "startYear": 2004,
    "runtimeMinutes": 109,
    "genre": "Comedy",
    "primaryCast": 14,
    "male": 7,
    "female": 7,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 5.9,
    "fullCast": 76,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Saving Bikini Bottom: The Sandy Cheeks Movie",
    "originalTitle": "Saving Bikini Bottom: The Sandy Cheeks Movie",
    "views": 18800000,
    "startYear": 2024,
    "runtimeMinutes": 82,
    "genre": "Animation",
    "primaryCast": 7,
    "male": 5,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 29,
    "rating": 3.7,
    "fullCast": 22,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Grown Ups 2",
    "originalTitle": "Grown Ups 2",
    "views": 18500000,
    "startYear": 2013,
    "runtimeMinutes": 101,
    "genre": "Comedy",
    "primaryCast": 7,
    "male": 4,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 43,
    "rating": 5.4,
    "fullCast": 100,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "It Ends with Us",
    "originalTitle": "It Ends with Us",
    "views": 18400000,
    "startYear": 2024,
    "runtimeMinutes": 130,
    "genre": "Romance",
    "primaryCast": 7,
    "male": 5,
    "female": 2,
    "nonbinary": 0,
    "percentageFemale": 29,
    "rating": 6.3,
    "fullCast": 26,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Trigger Warning",
    "originalTitle": "Trigger Warning",
    "views": 18400000,
    "startYear": 2024,
    "runtimeMinutes": 106,
    "genre": "Thriller",
    "primaryCast": 8,
    "male": 7,
    "female": 1,
    "nonbinary": 0,
    "percentageFemale": 13,
    "rating": 4.6,
    "fullCast": 39,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Alpha",
    "originalTitle": "Alpha",
    "views": 18400000,
    "startYear": 2018,
    "runtimeMinutes": 96,
    "genre": "Drama",
    "primaryCast": 6,
    "male": 2,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 67,
    "rating": 6,
    "fullCast": 32,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Aftermath",
    "originalTitle": "Aftermath",
    "views": 18400000,
    "startYear": 2024,
    "runtimeMinutes": 97,
    "genre": "Action",
    "primaryCast": 10,
    "male": 7,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 30,
    "rating": 5.2,
    "fullCast": 30,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Dhoom Dhaam",
    "originalTitle": "Dhoom Dhaam",
    "views": 18200000,
    "startYear": 2025,
    "runtimeMinutes": 108,
    "genre": "Romance",
    "primaryCast": 6,
    "male": 0,
    "female": 1,
    "nonbinary": 0,
    "percentageFemale": 17,
    "rating": 6.4,
    "fullCast": 35,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Revelations",
    "originalTitle": "Gyesirok",
    "views": 18000000,
    "startYear": 2025,
    "runtimeMinutes": 122,
    "genre": "Drama",
    "primaryCast": 8,
    "male": 5,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 38,
    "rating": 6,
    "fullCast": 18,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Life or Something Like It",
    "originalTitle": "Life or Something Like It",
    "views": 17900000,
    "startYear": 2002,
    "runtimeMinutes": 103,
    "genre": "Comedy",
    "primaryCast": 8,
    "male": 4,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 50,
    "rating": 5.8,
    "fullCast": 85,
    "leadGender": "female",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "The Cat in the Hat",
    "originalTitle": "The Cat in the Hat",
    "views": 17900000,
    "startYear": 2003,
    "runtimeMinutes": 82,
    "genre": "Comedy",
    "primaryCast": 7,
    "male": 4,
    "female": 3,
    "nonbinary": 0,
    "percentageFemale": 43,
    "rating": 4.2,
    "fullCast": 86,
    "leadGender": "male",
    "directorGender": "male",
    "netflicOriginal": "no"
  },
  {
    "primaryTitle": "Migration",
    "originalTitle": "Migration",
    "views": 17600000,
    "startYear": 2023,
    "runtimeMinutes": 83,
    "genre": "Animation",
    "primaryCast": 10,
    "male": 6,
    "female": 4,
    "nonbinary": 0,
    "percentageFemale": 40,
    "rating": 6.6,
    "fullCast": 41,
    "leadGender": "both",
    "directorGender": "male",
    "netflicOriginal": "no"
  }
];